FamilyLeads/force-app/main/default/objects/Child__c/Child__c.object-meta.xml
<CustomObject>
    <label>Child</label>
    <nameField>
        <displayFormat>CL-{00000}</displayFormat>
        <label>Child Lead Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Children</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FamilyLeads/force-app/main/default/objects/Child__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Children</relationshipLabel>
    <relationshipName>Children</relationshipName>
    <type>Lookup</type>
</CustomField>

FamilyLeads/force-app/main/default/classes/ChildTriggerHandler.cls
public with sharing class ChildTriggerHandler {

    public static void updateFamilyLead(List<Child__c> lstNewChildren) {

        List<Lead> lstLeadsToUpdate = new List<Lead>();

        Set<Id> setLeadIds = new Set<Id>();
        for (Child__c ch : lstNewChildren) {
            if (ch.Parent__c != null) {
                setLeadIds.add(ch.Parent__c);
            }
        }

        // If family lead is not already checked, check it
        for (List<Lead> lstLeads : [SELECT Id, Family_Lead__c FROM Lead WHERE Id IN :setLeadIds])
        {
            for (Lead ld : lstLeads) {
                if (ld.Family_Lead__c != true) {
                    ld.Child1_First_Name__c = 'FamilyLead';
                    lstLeadsToUpdate.add(ld);
                }
            }
        }
        if (!lstLeadsToUpdate.isEmpty()) {
            update lstLeadsToUpdate;
        }
    }
    
}